### ISSUE TITLE
Выполнение действия должно менять состояние объекта

### ISSUE THREAD

**Issue by AlphaBeth** [Vad1mChK/Lab03-04Progr#1]
https://github.com/Vad1mChK/Lab03Progr/blob/430b47db809a6f348736a1e805b510aea319a6b5/src/things/StoryCharacter.java#L45-L61

Как после выполнения этого метода понять, что, например, Карлсон действительно держит пылесос за ручку? А никак - эта информация простов выведется в консоль, не меняя состояния.

**Comment by Vad1mChK** [comment]
Добавлены свойства isFallenOnto, isHandleGrabbed, isOpen для пылесоса, которые изменяются при помощи сеттеров.
