### ISSUE TITLE
Получается, у вас каждый раз возникает новый пол?

### ISSUE THREAD

**Issue by AlphaBeth** [Vad1mChK/Lab03-04Progr#2]
https://github.com/Vad1mChK/Lab03Progr/blob/430b47db809a6f348736a1e805b510aea319a6b5/src/things/VacuumCleaner.java#L21

Просто попробуйте себе это представить: вы открываете пылесос, достаёте из него контейнер с мусором, переворачиваете его... И тут прямо под ним материализуется пол! Новый, чистый пол. И потом моментально исчезает.

**Comment by AlphaBeth** [comment]
В ту же степь
https://github.com/Vad1mChK/Lab03Progr/blob/430b47db809a6f348736a1e805b510aea319a6b5/src/things/Garbage.java#L7

**Comment by Vad1mChK** [comment]
Исправлено, теперь пол создаётся один раз и сохраняет мусор.
