### ISSUE TITLE
Должно менять состояние

### ISSUE THREAD

**Issue by AlphaBeth** [Vad1mChK/Lab03-04Progr#3]
https://github.com/Vad1mChK/Lab03Progr/blob/430b47db809a6f348736a1e805b510aea319a6b5/src/things/VacuumCleaner.java#L21

1. А если пылесос был пустым, то как это понять?
2. А как понять, что пылесос СТАЛ пустым после вызова метода?
3. А что конкретно высыпалось на пол? Как понять, что мусор из пылесоса теперь на полу?

**Comment by Vad1mChK** [comment]
Добавлено поле garbageList для VacuumCleaner, Floor, Wind, которое хранит список мусора, находящегося в данный момент в пылесосе/на полу/в воздухе. Теперь указано, что именно высыпано на пол.
