### ISSUE TITLE
Почему пыль возникает из ниоткуда и пропадает вникуда?

### ISSUE THREAD

**Issue by AlphaBeth** [Vad1mChK/Lab03-04Progr#5]
https://github.com/Vad1mChK/Lab03Progr/blob/430b47db809a6f348736a1e805b510aea319a6b5/src/things/Wind.java#L10

**Comment by Vad1mChK** [comment]
Исправлено, теперь пыль изначально находится в пылесосе, потом "передаётся" полу, ветру, затем снова полу.
