### ISSUE TITLE
Неэффективная реализация hashCode

### ISSUE THREAD

**Issue by AlphaBeth** [Vad1mChK/Lab03-04Progr#7]
https://github.com/Vad1mChK/Lab03Progr/blob/430b47db809a6f348736a1e805b510aea319a6b5/src/things/StoryCharacter.java#L88-L94

См. Joshua Bloch, Effective Java - там предложен достаточно эффективный в большинстве случаев алгоритм.

**Comment by Vad1mChK** [comment]
Ну, надеюсь, что теперь она более эффективная.
